server:
  port: 8888

spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  freemarker:
      templateLoaderPath: classpath:/templates/
      # 后缀
      suffix: .ftl
      charset: UTF-8
      request-context-attribute: request
      settings:
        number_format: 0.##########
      content-type: text/html